services:
  bot:
    build: .
    image: ghcr.io/infuseting/betterticket:latest
    container_name: betterticket-bot
    restart: always
    env_file:
      - .env
    volumes:
      - ./data:/app/data
    environment:
      - DATABASE_URL=file:/app/data/dev.db
